[project]
name = "piconumpy"
version = "0.0.0"
description = "An experiment about Numpy and pyhandle/hpy."
authors = [
    {name = "Pierre Augier", email = "pierre.augier@univ-grenoble-alpes.fr"},
]
license = {text = "BSD 3-Clause"}
readme = "README.md"
keywords = ["numpy", "hpy", "PyPy"]
requires-python = ">=3.8"

[project.urls]
homepage = "https://github.com/paugier/piconumpy"
repository = "https://github.com/paugier/piconumpy"
documentation = "https://github.com/paugier/piconumpy"

[project.optional-dependencies]
dev = ['transonic', 'numpy', 'pytest', 'pythran']
full = ['black']

[build-system]
requires = [
    "setuptools >= 35.0.2",
    "wheel",
    "cython",
    "hpy >= 0.9.0"
]

[tool.black]
line-length = 82
target_version = ['py310']
