name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.8', '3.9', '3.10', 'pypy-3.7-nightly']

    steps:

    - name: Setup Julia
      uses: julia-actions/setup-julia@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - if: startsWith(matrix.python-version, 'pypy') != true
      name: Install HPy (only for CPython)
      run: |
        # git clone -b release/0.0.3 --single-branch https://github.com/hpyproject/hpy
        # cd hpy
        # pip install .
        pip install hpy>=0.9.0rc1

    - name: Install dependencies
      run: |
        pip install numpy cython pytest transonic pythran

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: build
      run: |
        python setup.py develop
        python setup.py --hpy-abi=universal develop
        rm -f piconumpy/_piconumpy_hpy.py

    - name: Run tests
      run: |
        pytest -v

    - name: Run bench
      run: |
        cd bench
        make tmp_result_julia.txt
        make bench_hpy
        make
        # let's rerun bench_hpy to get these results also at the end
        make bench_hpy
