name: Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.11', '3.12', 'pypy-3.11']

    steps:

    - name: Setup Julia
      uses: julia-actions/setup-julia@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and install deps
      run: |
        pip install -e .[full]

    - if: startsWith(matrix.python-version, 'pypy') != true
      name: Build universal extension (only needed for CPython)
      run: |
        pip install -e . --config-settings="--global-option=--hpy-abi=universal"

    - name: Remove _piconumpy_hpy.py
      run: |
        rm -f piconumpy/_piconumpy_hpy.py

    - name: Run tests
      run: |
        pytest -v

    - name: Run bench
      run: |
        cd bench
        make tmp_result_julia.txt
        make bench_hpy
        make bench_full
        # rerun bench_hpy to get these results also at the end
        make bench_hpy
